In [1]:
#Ques 1
import numpy as np
arr=np.array([1,2,3,4,5])

print('Array + 2 : ',arr+2)
print('Array * 3 : ',arr*3)
print('Array / 2 : ',arr/2)

Array + 2 :  [3 4 5 6 7]
Array * 3 :  [ 3  6  9 12 15]
Array / 2 :  [0.5 1.  1.5 2.  2.5]


In [11]:
#Ques 2
import numpy as np
arr=np.array([1,2,3,6,4,5])

rev=np.flip(arr)       # or arr[::-1]
print('Reversed:',rev)


x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

max_x=np.bincount(x).argmax()
max_y=np.bincount(y).argmax()

indices_x=np.where(x==max_x)[0]
indices_y=np.where(y==max_y)[0]
print('In X:')
print('Most Frequent: ',max_x)
print('Indices: ',indices_x)
print()
print('In Y:')
print('Most Frequent: ',max_y)
print('Indices: ',indices_y)

Reversed: [5 4 6 3 2 1]
In X:
Most Frequent:  1
Indices:  [0 5 7 8 9]

In Y:
Most Frequent:  1
Indices:  [0 1 2]


In [22]:
#Ques 3
import numpy as np
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])

print(arr[0][1])
print(arr[2][0])

20
70


In [25]:
#Ques 4
import numpy as np
hitesh=np.linspace(10,100,25)

print('Array:',hitesh)

#Array attributes
print('Dimension: ',hitesh.ndim)
print('Shape :',hitesh.shape)
print('Number of elements:',hitesh.size)
print('Data Type:',hitesh.dtype)
print('Total bytes: ',hitesh.nbytes)


#using reshape
hitesh_t=hitesh.reshape(25,1)
print('Using reshape:')
print(hitesh_t)
print()

print('Using T:')
t=hitesh.T
print(t)
print()

print('T not applicable to 1D array')


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension:  1
Shape : (25,)
Number of elements: 25
Data Type: float64
Total bytes:  200
Using reshape:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

T not applicable to 1D array


In [30]:
#Ques 5
import numpy as np
ucs420_hitesh=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_hitesh)
print('Mean : ',np.mean(ucs420_hitesh))
print('Median : ',np.median(ucs420_hitesh))
print('Max : ',np.max(ucs420_hitesh))
print('Min : ',np.min(ucs420_hitesh))
print('Unique elements: ',np.unique(ucs420_hitesh))
print()

#Reshape
reshaped_ucs420_hitesh=ucs420_hitesh.reshape(4,3)
resized_ucs420_hitesh=np.resize(ucs420_hitesh,(2,3))
print('Reshaped:')
print(reshaped_ucs420_hitesh)
print()

print('Resized:')
print(resized_ucs420_hitesh)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean :  43.333333333333336
Median :  37.5
Max :  90
Min :  10
Unique elements:  [10 15 20 30 35 40 50 60 70 80 90]

Reshaped:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized:
[[10 20 30]
 [40 50 60]]
